using System.Collections.Generic;

namespace ChartJSCore.Models
{
    public class CartesianScale : Scale
    {
        /// <summary>
        /// Type of scale being employed. Custom scales can be created and registered with a string key. Options: "category", "linear", "logarithmic", "time", "radialLinear".
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// Position of the scale. Possible values are 'top', 'left', 'bottom' and 'right'.
        /// </summary>
        public string Position { get; set; }

        /// <summary>
        /// If true, extra space is added to the both edges and the axis is scaled to fit into the chart area. This is set to true in the bar chart by default.
        /// </summary>
        public bool? Offset { get; set; }

        /// <summary>
        /// The ID is used to link datasets and scale axes together. The properties datasets.xAxisID or datasets.yAxisID have to match the scale properties scales.xAxes.id or scales.yAxes.id. This is especially needed if multi-axes charts are used.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// The grid line configuration is nested under the scale configuration in the gridLines key. It defines options for the grid lines that run perpendicular to the axis.
        /// </summary>
        public IList<GridLine> GridLines { get; set; }

        /// <summary>
        /// The scale label configuration is nested under the scale configuration in the scaleLabel key. It defines options for the scale title.
        /// </summary>
        public ScaleLabel ScaleLabel { get; set; }

        /// <summary>
        /// The tick configuration is nested under the scale configuration in the ticks key. It defines options for the tick marks that are generated by the axis.
        /// </summary>
        public Tick Ticks { get; set; }
    }
}
